// project/src/App.tsx
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import Login from './page/Login';
import Template from './page/Template';
import PageData from './PageData';

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route index element={<Template />} />
        <Route path="/login" element={<Login />} />
        {PageData.map(({ element, path }) => (
          <Route path={path} element={element} />
        ))}
      </Routes>
    </BrowserRouter>
  );
}

export default App;

// fe/src/App.vue
<script setup lang="ts">
</script>

<template>
  <template v-if="$route.path === '/login'">
    <router-view :key="$route.path" />
  </template>
  <template v-else>
    <div class="app">
      <router-view :key="$route.path" />
    </div>
  </template>
</template>

<style lang="scss" scoped>
</style>
