// src/Component/Header.tsx
import styled from "styled-components";

const TopNavigationBar = styled.h1`
  font-size: 20px;
  font-style: italic;
  color: black;
  padding: 20px;
  border-bottom: 2px solid gray;
  font-weight: bold;
`;

function Header() {
  return (
    <>
      <TopNavigationBar>Wanted pre-onboarding-course</TopNavigationBar>
    </>
  );
}

export default Header;

// wanted_march/src/layout/Header.vue
<script setup lang="ts"></script>

<template>
  <div class="container">
    <h2>Wanted-Pre-onboarding Course</h2>
  </div>
</template>

<style lang="scss">
.container {
  top: 0;
  padding: 20px;
  border: 1px solid #000000;
  position: fixed;
  z-index: 10;
  background-color: #ffffff;
  h1 {
    font-size: 4rem;
  }
}
</style>
