// fe/src/App.vue
<script setup lang="ts">
</script>

<template>
  <template v-if="$route.path === '/login'">
    <router-view :key="$route.path" />
  </template>
  <template v-else>
    <div class="app">
      <router-view :key="$route.path" />
    </div>
  </template>
</template>

<style lang="scss" scoped>
</style>

// wanted/src/App.jsx
import React from 'react';
import { Route } from 'react-router';
import $ from './app.module.scss'
import Header from './components/Header';
import SideBar from './components/SideBar';

const App = () => {
  return (
    <div>
      <Header />
      <div className={$.wrapper}>
        <SideBar />
        <div className={$.contents}>
          {/* <Route path='' element={} /> */}
        </div>
      </div>
    </div>
  );
}

export default App;
