// fe/src/App.vue
<script setup lang="ts">
</script>

<template>
  <template v-if="$route.path === '/login'">
    <router-view :key="$route.path" />
  </template>
  <template v-else>
    <div class="app">
      <router-view :key="$route.path" />
    </div>
  </template>
</template>

<style lang="scss" scoped>
</style>

// wanted-pre-onboarding/src/App.tsx
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";
import "./App.css";

import Layout from "./layout/Layout";
import Home from "./pages/Home";
import LoginPage from "./pages/LoginPage";
import PageA from "./pages/PageA";
import PageB from "./pages/PageB";
import PageC from "./pages/PageC";

function App() {
  return (
    <Router>
      <Routes>
        <Route element={<Layout />}>
          <Route path="/" element={<Home />} />
          <>
            <Route path="/pageA" element={<PageA />} />
            <Route path="/pageB" element={<PageB />} />
            <Route path="/pageC" element={<PageC />} />
          </>
          <Route path="/login" element={<LoginPage />} />
        </Route>
      </Routes>
    </Router>
  );
}

export default App;
